### ISSUE TITLE
BETSI shuts down if it can't find a valid area

### ISSUE THREAD

**Issue by sblanky** [nakulrampal/betsi-gui#5]
Thanks so much for making this software, absolutely vital!

If the restrictions are too narrow, so a valid BET area can't be found betsi will shut down. This is somewhat frustrating when trying to analyse isotherms.

```
Imported file: some_file.csv
Traceback (most recent call last):
  File "/home/pcxtsbl/anaconda3/envs/betsi/lib/python3.7/site-packages/betsi/gui.py", line 118, in dropEvent
    self.betsi_widget.run_calculation()
  File "/home/pcxtsbl/anaconda3/envs/betsi/lib/python3.7/site-packages/betsi/gui.py", line 343, in run_calculation
    max_perc_error=max_perc_error)
  File "/home/pcxtsbl/anaconda3/envs/betsi/lib/python3.7/site-packages/betsi/lib.py", line 221, in __init__
    assert np.sum(filter_mask) != 0, "NO valid areas found"
AssertionError: NO valid areas found
Aborted (core dumped)

```

Suggest might be easier to have an error message, and show what criteria the isotherm failed. Then allow user to adjust parameters.

**Comment by nakulrampal** [comment]
Thanks for the suggestion, @sblanky - I think that's a great idea - it would be good to have an error message pop up instead of just having the program shut down
