### ISSUE TITLE
Problem with BETSI install

### ISSUE THREAD

**Issue by gianmarco-terrones** [nakulrampal/betsi-gui#6]
As I was following the instructions in the main README, I entered the following command in the terminal: `pip install -i https://test.pypi.org/simple/ betsi-gui`. Unfortunately, this led to the following error message:

```
(betsi) gianmarcoterrones@dhcp-10-29-1-210 MOFs % pip install -i https://test.pypi.org/simple/ betsi-gui
Looking in indexes: https://test.pypi.org/simple/
Collecting betsi-gui
  Downloading https://test-files.pythonhosted.org/packages/b6/e9/c3c1512e2786fc04f5f828061162edcadf37c3849be17d7a7d225849d9be/betsi_gui-1.0.20-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.6/41.6 kB 959.0 kB/s eta 0:00:00
  Downloading https://test-files.pythonhosted.org/packages/14/95/09f52a3e0dcb413fea314e2bdbb82127a6fc8d8501220c6a70052da38ca0/betsi_gui-1.0.19-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.6/41.6 kB 955.8 kB/s eta 0:00:00
  Downloading https://test-files.pythonhosted.org/packages/ce/a8/4c7faa6c5b4ef5bdd63875090303be7f9844e6cd891f891493dd6e8befcc/betsi_gui-1.0.18-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 1.1 MB/s eta 0:00:00
  Downloading https://test-files.pythonhosted.org/packages/3c/30/4affcc206b4a49832cac2c15ecff26d93166535a6a1b65bf0614733ea740/betsi_gui-1.0.17-py3-none-any.whl (20 kB)
  Downloading https://test-files.pythonhosted.org/packages/a9/39/ef28a70f2b9913b6e9051bc689f79e210f4bb918f6556c672cfb79c89262/betsi_gui-1.0.16-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/3a/4f/f02d72175055f90fa642ef1335cbabd03054f8348ec965ca519388d8f93d/betsi_gui-1.0.15-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/e4/fc/c05b94226ee2cd1bdeef2db8d78f148d829146c2bc3682995ad3505bc42d/betsi_gui-1.0.14-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/ff/f1/279136b7bbd1a13cbb386c8ad8013100e4ebc276f4035d1b419486ae56d2/betsi_gui-1.0.13-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/18/66/f7e8c715bec2a970ee50ca4b76e0a594d8a03d961ec3ef59e103533f82d1/betsi_gui-1.0.12-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/82/1e/4ad582a65611289d22b85d83903f6e88af3aa870eddacf0841300a300a8e/betsi_gui-1.0.11-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/1b/ba/6b59556671675974e12ca672f48da8ebcf193f8ef5e4f182fa3e609a8f28/betsi_gui-1.0.10-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/ca/6b/9e8050defad05f76ea4ff8169517efc579b4826f6ebe5d68896b35b04007/betsi_gui-1.0.9-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/71/31/9d11a28592cddf05b307920355e661745ba038b2b36b09748baef68275b9/betsi_gui-1.0.8-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/db/68/228561c61505a5e9aa12dc98b210a560fc4c28fe2df1ab22c19a26c8c816/betsi_gui-1.0.7-py3-none-any.whl (3.1 kB)
  Downloading https://test-files.pythonhosted.org/packages/83/4b/fa283e73f64fb118ec39c9ada83d7c801be52a9537492dfb703e74563b1b/betsi_gui-1.0.6-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/0d/bd/e8c5a8ad3a3a9a4311d27f360fee24cfdb2ca0061e05440865a5965d50ee/betsi_gui-1.0.5-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/09/28/cf6adb1531577d70e925b3a04418404879112fdf6a52cc4ee617b0fdf205/betsi_gui-1.0.4-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/3e/2f/25c231a6eaf30da69af8a6f3cb4fc183e4024395c7da8d444e0f35c1a701/betsi_gui-1.0.3-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/2b/b2/bc5402b8b77c2bec4dd06daa20ed160d5ce1d497fbb2f82a0f20f0ef5dcb/betsi_gui-1.0.2-py3-none-any.whl (3.2 kB)
  Downloading https://test-files.pythonhosted.org/packages/9a/e6/5e23d1df4fc34f75b96bb9494aa54e48032e2664341ebc0b6cd5f41bfaf8/betsi_gui-1.0.1-py3-none-any.whl (19 kB)
  Downloading https://test-files.pythonhosted.org/packages/e2/78/19ee7af7398bdca9714ba4e18a052a8c17a9f62bf9a0efe663fdf13193df/betsi_gui-1.0.0-py3-none-any.whl (19 kB)
ERROR: Cannot install betsi-gui==1.0.0, betsi-gui==1.0.1, betsi-gui==1.0.10, betsi-gui==1.0.11, betsi-gui==1.0.12, betsi-gui==1.0.13, betsi-gui==1.0.14, betsi-gui==1.0.15, betsi-gui==1.0.16, betsi-gui==1.0.17, betsi-gui==1.0.18, betsi-gui==1.0.19, betsi-gui==1.0.2, betsi-gui==1.0.20, betsi-gui==1.0.3, betsi-gui==1.0.4, betsi-gui==1.0.5, betsi-gui==1.0.6, betsi-gui==1.0.7, betsi-gui==1.0.8 and betsi-gui==1.0.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    betsi-gui 1.0.20 depends on matplotlib==3.2.2
    betsi-gui 1.0.19 depends on matplotlib==3.2.2
    betsi-gui 1.0.18 depends on matplotlib==3.2.2
    betsi-gui 1.0.17 depends on matplotlib==3.2.2
    betsi-gui 1.0.16 depends on matplotlib==3.2.2
    betsi-gui 1.0.15 depends on pandas==1.1.5
    betsi-gui 1.0.14 depends on scipy==1.4.1
    betsi-gui 1.0.13 depends on numpy>=1.18.1
    betsi-gui 1.0.12 depends on numpy==1.17.2
    betsi-gui 1.0.11 depends on numpy==1.17.2
    betsi-gui 1.0.10 depends on numpy==1.17.2
    betsi-gui 1.0.9 depends on numpy==1.17.2
    betsi-gui 1.0.8 depends on numpy==1.17.2
    betsi-gui 1.0.7 depends on pandas
    betsi-gui 1.0.6 depends on numpy>=1.18.1
    betsi-gui 1.0.5 depends on scipy==1.4.1
    betsi-gui 1.0.4 depends on scipy==1.4.1
    betsi-gui 1.0.3 depends on scipy==1.4.1
    betsi-gui 1.0.2 depends on scipy==1.4.1
    betsi-gui 1.0.1 depends on pandas
    betsi-gui 1.0.0 depends on pandas

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

So it seems that `pip install -i https://test.pypi.org/simple/ betsi-gui` is not working at the moment?

**Comment by gianmarco-terrones** [comment]
As an aside, option 2 (installing from source code) worked for me, but I had to first run
```
brew install git-lfs
git lfs install
```
in order for `git clone` to work properly. I am working on a Mac.

**Comment by nakulrampal** [comment]
Hi, @gianmarco-terrones - let me begin by first apologizing for the delay in getting back - thank you for bringing this to our attention. We will work on a fix for this ASAP

**Comment by gianmarco-terrones** [comment]
No worries, the fix is not time sensitive for me since option 2 worked :) Thank you for developing this tool

**Comment by himanshibhambri92** [comment]
Hello,
During installation, following the instructions, I am finding some issues after the command python -m betsi. Please see the following.

(BETSI) C:\Users\hp\betsi-gui-master>python -m betsi
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\envs\BETSI\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\hp\anaconda3\envs\BETSI\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hp\betsi-gui-master\betsi\__main__.py", line 1, in <module>
    from betsi.gui import runbetsi
  File "C:\Users\hp\betsi-gui-master\betsi\gui.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\hp\anaconda3\envs\BETSI\lib\site-packages\matplotlib-3.2.2-py3.7-win-amd64.egg\matplotlib\__init__.py", line 139, in <module>
    from . import cbook, rcsetup
  File "C:\Users\hp\anaconda3\envs\BETSI\lib\site-packages\matplotlib-3.2.2-py3.7-win-amd64.egg\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "C:\Users\hp\anaconda3\envs\BETSI\lib\site-packages\matplotlib-3.2.2-py3.7-win-amd64.egg\matplotlib\fontconfig_pattern.py", line 18, in <module>
    from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
  File "C:\Users\hp\anaconda3\envs\BETSI\lib\site-packages\pyparsing-3.2.3-py3.7.egg\pyparsing\__init__.py", line 129, in <module>
    from .util import *
  File "C:\Users\hp\anaconda3\envs\BETSI\lib\site-packages\pyparsing-3.2.3-py3.7.egg\pyparsing\util.py", line 15, in <module>
    class __config_flags:
  File "C:\Users\hp\anaconda3\envs\BETSI\lib\site-packages\pyparsing-3.2.3-py3.7.egg\pyparsing\util.py", line 18, in __config_flags
    _all_names: list[str] = []
TypeError: 'type' object is not subscriptable

(BETSI) C:\Users\hp\betsi-gui-master>

If possible, kindly help.

**Comment by nakulrampal** [comment]
Hi, @himanshibhambri92 — Thank you for bringing this to our attention. I will have a look at this now. In the meantime, you may want to use the executable files to run BETSI.

**Comment by himanshibhambri92** [comment]
Hello sir,
Thank you for your prompt response.

The executables are not compatible with the version for my PC (the
notification comes when I try to run the application).

Moreover, I have limited knowledge with this.
